version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: redhat
      POSTGRES_PASSWORD: redhat
    volumes:
      - ./demo/postgres:/docker-entrypoint-initdb.d/
  mariadb:
    container_name: mariadb
    image: mariadb:10.3.8
    environment:
      MYSQL_ROOT_PASSWORD: redhat
      MYSQL_USER: redhat
      MYSQL_PASSWORD: redhat
    ports:
      - "3306:3306"
    volumes:
      - ./demo/mariadb:/docker-entrypoint-initdb.d
